import os
from dotenv import load_dotenv

load_dotenv()

CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY", "")
WHOOP_CLIENT_ID = os.getenv("WHOOP_CLIENT_ID", "")
WHOOP_CLIENT_SECRET = os.getenv("WHOOP_CLIENT_SECRET", "")

CAPTURE_INTERVAL_DEFAULT = 3
CAPTURE_WIDTH = 1280
JPEG_QUALITY = 60
HASH_THRESHOLD = 5

INTERVENTION_COOLDOWN = 30
VISION_MODEL = "claude-sonnet-4-20250514"
VISION_MAX_TOKENS = 500
GHOST_MAX_TOKENS_DEFAULT = 100

HRV_BASELINE_WINDOW = 14
STRESS_HIGH_THRESHOLD = 2.0
STRESS_MEDIUM_THRESHOLD = 1.0
STRESS_FIREWALL_THRESHOLD = 2.0

WHOOP_TOKEN_REFRESH_BUFFER = 60
WHOOP_API_VERSION = "v2"
WHOOP_RATE_LIMIT_PER_MIN = 100
WHOOP_RATE_LIMIT_PER_DAY = 10000

HOST = "0.0.0.0"
PORT = 8000

USE_MOCK_BIOMETRICS = True

GAME_MODE = True
GAME_APPS = ["code", "terminal", "browser", "notes", "chat"]
CONTENT_REANALYZE_INTERVAL = 15
CONTENT_MIN_LENGTH = 10
